/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlacesRouteImport } from './routes/places'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PlacesRoute = PlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlacesRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/places': typeof PlacesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/places': typeof PlacesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/places': typeof PlacesRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/places/$id': typeof PlacesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/places' | '/api/chat' | '/places/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/places' | '/api/chat' | '/places/$id'
  id: '__root__' | '/' | '/places' | '/api/chat' | '/places/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlacesRoute: typeof PlacesRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/places': {
      id: '/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof PlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof PlacesRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlacesRouteChildren {
  PlacesIdRoute: typeof PlacesIdRoute
}

const PlacesRouteChildren: PlacesRouteChildren = {
  PlacesIdRoute: PlacesIdRoute,
}

const PlacesRouteWithChildren =
  PlacesRoute._addFileChildren(PlacesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlacesRoute: PlacesRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
