-- Reset places and reseed with refined 8-category taxonomy
-- Categories: beach, nature, temple, history, food, cafe, nightlife, fruit
-- Cross-cutting tags carry secondary intents (hiking, camping, view, family, romantic, etc.)

DELETE FROM public.favorites;
DELETE FROM public.places;

INSERT INTO public.places (slug, name_th, name_en, category, district, description_th, description_en, image_url, lat, lng, opening_hours, price_info, address, tags, rating, is_free, featured) VALUES

-- ============= BEACH (7) =============
('chao-lao-beach', 'หาดเจ้าหลาว', 'Chao Lao Beach', 'beach', 'ท่าใหม่',
  'ชายหาดยอดนิยมอันดับหนึ่งของจันทบุรี โดดเด่นด้วยหาดทรายสีเหลืองนวลละเอียด น้ำทะเลใสสะอาด บรรยากาศเงียบสงบ เหมาะสำหรับการพาครอบครัวมาพักผ่อนและรับประทานอาหารทะเลสด',
  'Chanthaburi''s most popular beach with fine yellow sand and clear waters. Quiet atmosphere, perfect for family getaways and fresh seafood meals.',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200',
  12.4517, 101.8492, '24 ชั่วโมง', 'ฟรี', 'ต.คลองขุด อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['seaside','family','swimming','sunset','seafood','camping'], 4.7, true, true),

('laem-sadet-beach', 'หาดแหลมเสด็จ', 'Laem Sadet Beach', 'beach', 'ท่าใหม่',
  'หาดประวัติศาสตร์ที่รัชกาลที่ 5 เคยเสด็จประพาส มีศาลาเสด็จเป็นเอกลักษณ์ ทรายละเอียด สงบเงียบกว่าหาดอื่น เหมาะกับการพักผ่อนแบบเงียบสงบ',
  'A historic beach where King Rama V once visited, featuring the iconic Sala Sadet pavilion. Fine sand and quieter than other beaches — perfect for relaxation.',
  'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200',
  12.5408, 101.8869, '24 ชั่วโมง', 'ฟรี', 'ต.คลองขุด อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['seaside','historic','quiet','photo'], 4.6, true, true),

('kung-wiman-beach', 'หาดคุ้งวิมาน', 'Kung Wiman Beach', 'beach', 'นายายอาม',
  'หาดเงียบสงบที่ถูกล้อมด้วยภูเขาทั้งสองข้าง น้ำทะเลใส มีจุดชมวิวเนินนางพญาที่สวยงาม เหมาะกับการถ่ายภาพ',
  'A serene beach surrounded by mountains on both sides with clear waters. Near the famous Noen Nangphaya viewpoint — great for photography.',
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
  12.5950, 101.9133, '24 ชั่วโมง', 'ฟรี', 'อ.นายายอาม จ.จันทบุรี',
  ARRAY['seaside','mountain','photo','quiet'], 4.7, true, false),

('laem-sing-beach', 'หาดแหลมสิงห์', 'Laem Sing Beach', 'beach', 'แหลมสิงห์',
  'ปากแม่น้ำที่บรรจบกับทะเล มีตึกแดงและคุกขี้ไก่ที่เป็นโบราณสถานสมัยฝรั่งเศสยึดครอง บรรยากาศคลาสสิก',
  'Where the river meets the sea, home to the Red Building and Kuk Khi Kai (old French-era prison). A classic atmospheric spot.',
  'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=1200',
  12.4717, 102.0628, '24 ชั่วโมง', 'ฟรี', 'อ.แหลมสิงห์ จ.จันทบุรี',
  ARRAY['seaside','historic','photo'], 4.4, true, false),

('noen-nangphaya', 'จุดชมวิวเนินนางพญา', 'Noen Nangphaya Viewpoint', 'beach', 'นายายอาม',
  'แลนด์มาร์กสุดโรแมนติกบนถนนเฉลิมบูรพาชลทิตซึ่งเป็นถนนเลียบชายทะเลที่สวยที่สุดในไทย ให้ภาพมุมสูงของถนนที่คดเคี้ยวเลียบภูเขาตัดกับน้ำทะเลสีครามสุดลูกหูลูกตา',
  'A romantic landmark on Chalerm Burapha Chonlathit Road, Thailand''s most beautiful coastal road, offering elevated views of the winding road set against endless blue waters.',
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200',
  12.5683, 102.0903, '24 ชั่วโมง', 'ฟรี', 'ถนนเฉลิมบูรพาชลทิต อ.นายายอาม จ.จันทบุรี',
  ARRAY['view','sunset','sunrise','photo','romantic','mountain'], 4.8, true, true),

('hin-khrong-viewpoint', 'จุดชมวิวหินโคร่ง', 'Hin Khrong Viewpoint', 'beach', 'นายายอาม',
  'จุดชมพระอาทิตย์ตกที่งดงาม เต็มไปด้วยโขดหินแกรนิตน้อยใหญ่เรียงรายตามแนวชายหาด เป็นสถานที่ยอดฮิตสำหรับสายตกปลาและคนที่ชอบมานั่งปิกนิกรับลมทะเลยามเย็น',
  'A stunning sunset spot lined with granite boulders along the shore. Popular among anglers and picnickers seeking the cool sea breeze in the evening.',
  'https://images.unsplash.com/photo-1502691876148-a84978e59af8?w=1200',
  12.5400, 101.9000, '24 ชั่วโมง', 'ฟรี', 'อ.นายายอาม จ.จันทบุรี',
  ARRAY['view','sunset','photo','fishing','picnic'], 4.5, true, false),

('ban-hua-laem-pagoda', 'เจดีย์กลางน้ำบ้านหัวแหลม', 'Ban Hua Laem Sea Pagoda', 'beach', 'ท่าใหม่',
  'สถานที่ท่องเที่ยวสุดอันซีนที่มีเจดีย์เก่าแก่อายุกว่าร้อยปีประดิษฐานอยู่บนโขดหินกลางทะเล มีสะพานไม้ทอดยาวให้เดินรับลมและชมวิวทะเลแบบพาโนรามา เชื่อกันว่าช่วยเรียกขวัญชาวประมงก่อนออกเรือ',
  'An unseen gem featuring a century-old pagoda on rocks in the sea. A wooden boardwalk extends out for panoramic ocean views. Locals believe it brings fortune to fishermen before they sail.',
  'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200',
  12.4533, 101.9367, '24 ชั่วโมง', 'ฟรี', 'อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['hidden-gem','seaside','spiritual','photo','sunrise'], 4.7, true, true),

-- ============= NATURE (7) =============
('phlio-waterfall', 'อุทยานแห่งชาติน้ำตกพลิ้ว', 'Phlio Waterfall National Park', 'nature', 'แหลมสิงห์',
  'น้ำตกชื่อดังที่มีสายน้ำใสสะอาดตลอดปี เป็นแหล่งอาศัยของปลาพลวงจำนวนมาก มีความสำคัญทางประวัติศาสตร์ด้วยเจดีย์อลงกรณ์ที่สร้างขึ้นในสมัยรัชกาลที่ 5 เหมาะแก่การพักผ่อน',
  'A famous year-round waterfall, home to a massive school of soro brook carp. Historically significant for the Alongkorn Chedi built by King Rama V. Perfect for relaxation.',
  'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=1200',
  12.5353, 102.2322, '08:00-17:00', 'คนไทย 40฿ ต่างชาติ 200฿',
  'อุทยานแห่งชาติน้ำตกพลิ้ว อ.แหลมสิงห์ จ.จันทบุรี',
  ARRAY['waterfall','swimming','hiking','historic','family'], 4.8, false, true),

('krating-waterfall', 'น้ำตกกระทิง', 'Krating Waterfall', 'nature', 'เขาคิชฌกูฏ',
  'น้ำตกขนาดใหญ่ที่ลดหลั่นกันถึง 13 ชั้น ท่ามกลางผืนป่าที่เงียบสงบในอุทยานแห่งชาติเขาคิชฌกูฏ มีเส้นทางศึกษาธรรมชาติที่สมบูรณ์ เหมาะสำหรับการเล่นน้ำและพักผ่อนหย่อนใจ',
  'A grand 13-tier waterfall in the peaceful forests of Khao Khitchakut National Park. Rich nature trails — perfect for swimming and unwinding.',
  'https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=1200',
  12.8167, 102.1500, '08:00-17:00', 'คนไทย 40฿ ต่างชาติ 200฿',
  'อุทยานแห่งชาติเขาคิชฌกูฏ จ.จันทบุรี',
  ARRAY['waterfall','swimming','hiking','camping'], 4.7, false, false),

('khao-soi-dao-waterfall', 'น้ำตกเขาสอยดาว', 'Khao Soi Dao Waterfall', 'nature', 'สอยดาว',
  'น้ำตก 16 ชั้นที่ยิ่งใหญ่ที่สุดในจันทบุรี ขึ้นได้ถึงชั้น 5-6 ตามความฟิต บริเวณรอบมีสภาพป่าสมบูรณ์ อากาศเย็นสบาย',
  'The grandest waterfall in Chanthaburi with 16 tiers. Most visitors hike to tiers 5-6 depending on fitness. Surrounded by pristine forest with cool air.',
  'https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1200',
  13.0500, 102.2167, '08:00-16:30', 'คนไทย 40฿ ต่างชาติ 200฿',
  'อ.สอยดาว จ.จันทบุรี',
  ARRAY['waterfall','hiking','adventure','camping'], 4.7, false, false),

('pha-hin-kub', 'ผาหินกูบ', 'Pha Hin Kub Cliff', 'nature', 'สอยดาว',
  'จุดชมวิวระดับอันซีนในเขตรักษาพันธุ์สัตว์ป่าเขาสอยดาว โดดเด่นด้วยก้อนหินแกรนิตยักษ์รูปกูบช้างที่ความสูง 960 เมตรจากระดับน้ำทะเล นำเสนอทัศนียภาพทะเลหมอกที่งดงามเหนือขุนเขา ต้องเดินป่าระยะ 6-7 กม. กับเจ้าหน้าที่นำทาง',
  'An unseen viewpoint inside Khao Soi Dao Wildlife Sanctuary featuring giant granite rocks shaped like an elephant howdah at 960m elevation. Stunning sea-of-clouds views. Requires a 6-7km guided trek.',
  'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200',
  12.9500, 102.2000, 'เสาร์-อาทิตย์ (ตามประกาศ)', 'ติดต่อเจ้าหน้าที่นำทาง',
  'เขตรักษาพันธุ์สัตว์ป่าเขาสอยดาว อ.สอยดาว จ.จันทบุรี',
  ARRAY['hidden-gem','hiking','adventure','camping','view','sunrise','mountain'], 4.9, false, true),

('kung-krabaen-bay', 'อ่าวคุ้งกระเบน', 'Kung Krabaen Bay & Mangrove Trail', 'nature', 'ท่าใหม่',
  'สะพานไม้ทอดยาวผ่านป่าชายเลนอันเงียบสงบ เดินง่าย เหมาะสำหรับนักท่องเที่ยวทุกวัยที่ต้องการศึกษาความหลากหลายทางชีวภาพของระบบนิเวศชายฝั่งและการอนุรักษ์พันธุ์สัตว์น้ำ ภายในศูนย์ศึกษาการพัฒนาอันเนื่องมาจากพระราชดำริ',
  'A wooden boardwalk through serene mangrove forest. Easy walk for all ages, ideal for studying coastal ecosystem biodiversity and aquatic conservation. Part of the Royal Development Study Center.',
  'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200',
  12.5481, 101.8961, '08:30-16:30', 'ฟรี', 'ต.คลองขุด อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['mangrove','family','easy-walk','education','seaside'], 4.6, true, true),

('khao-sip-ha-chan', 'อุทยานแห่งชาติเขาสิบห้าชั้น', 'Khao Sip Ha Chan National Park', 'nature', 'เขาคิชฌกูฏ',
  'พื้นที่กางเต็นท์ริมลำธารที่เงียบสงบและร่มรื่นด้วยต้นไม้ใหญ่ ภายในอุทยานมีสิ่งอำนวยความสะดวกครบครันในราคาที่ย่อมเยา มีน้ำตก 15 ชั้นให้พิชิต ตอนกลางคืนสามารถสัมผัสวิถีชีวิตสัตว์ป่าได้อย่างใกล้ชิด',
  'Quiet streamside camping area shaded by giant trees with full facilities at affordable prices. Conquer the 15-tier waterfall by day, observe wildlife at night.',
  'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=1200',
  12.6500, 102.3000, '06:00-20:00', 'เข้า 20฿ กางเต็นท์ 30฿/คน',
  'อ.เขาคิชฌกูฏ จ.จันทบุรี',
  ARRAY['camping','hiking','waterfall','wildlife','budget'], 4.6, false, false),

('pink-stone-beach', 'ลานหินสีชมพู', 'Pink Stone Beach', 'nature', 'ท่าใหม่',
  'จุดกางเต็นท์ริมทะเลสุดพิเศษในเขตห้ามล่าสัตว์ป่าคุ้งกระเบน เดินสำรวจโขดหินทรายอาร์โคสที่ทำปฏิกิริยากับออกซิเจนจนเกิดสีชมพูอมน้ำตาลแดง เหมาะสำหรับผู้ที่ชื่นชอบการตื่นมาชมแสงแรกของวันริมชายหาด',
  'Special seaside camping spot in Kung Krabaen Wildlife Sanctuary. Explore arkosic sandstone rocks that oxidize into pink-brown hues. Ideal for catching first light of day by the shore.',
  'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
  12.5500, 101.9100, 'ขึ้นกับน้ำขึ้นน้ำลง', 'ฟรี',
  'เขตห้ามล่าสัตว์ป่าคุ้งกระเบน อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['hidden-gem','seaside','camping','sunrise','photo','geology'], 4.6, true, false),

-- ============= TEMPLE (4) =============
('khao-khitchakut', 'รอยพระพุทธบาท เขาคิชฌกูฏ', 'Khao Khitchakut Buddha Footprint', 'temple', 'เขาคิชฌกูฏ',
  'ปูชนียสถานศักดิ์สิทธิ์ที่สูงที่สุดในประเทศไทย ตั้งอยู่บนยอดเขาที่สูงกว่า 1,050 เมตร เปิดให้สักการะเพียงปีละหนึ่งครั้งในช่วงก่อนเทศกาลสงกรานต์ (ก.พ.-เม.ย.) ผู้แสวงบุญนับแสนเดินทางมาเพื่อขอพรเสริมสิริมงคล มีปรากฏการณ์หินลูกบาตรน่าอัศจรรย์',
  'Thailand''s highest sacred shrine atop a 1,050m mountain. Open for pilgrimage only February-April each year. Hundreds of thousands of pilgrims travel here seeking blessings, alongside the wondrous balancing stone phenomenon.',
  'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200',
  12.8389, 102.1444, 'ก.พ.-เม.ย. (ตามประกาศ)', 'ฟรี (มีค่ารถขึ้นเขา)',
  'อุทยานแห่งชาติเขาคิชฌกูฏ จ.จันทบุรี',
  ARRAY['spiritual','pilgrimage','mountain','hiking','sacred'], 4.9, false, true),

('cathedral-immaculate', 'อาสนวิหารพระนางมารีอาปฏิสนธินิรมล', 'Cathedral of the Immaculate Conception', 'temple', 'เมืองจันทบุรี',
  'โบสถ์คริสต์สไตล์โกธิกที่ใหญ่ที่สุดในประเทศ อายุกว่าร้อยปี เปิดอย่างเป็นทางการในปี พ.ศ. 2452 ภายในตกแต่งอย่างอลังการด้วยกระจกสีสเตนกลาส และมีองค์พระแม่มารีที่ประดับด้วยอัญมณีท้องถิ่นกว่า 200,000 เม็ดมูลค่ามหาศาล',
  'Thailand''s largest Gothic-style cathedral, over 100 years old (officially opened in 1909). Adorned with magnificent stained glass and a Virgin Mary statue decorated with over 200,000 local gemstones.',
  'https://images.unsplash.com/photo-1548013146-72479768bada?w=1200',
  12.6072, 102.1097, '06:00-18:00', 'ฟรี', 'ถ.สันติชล ต.จันทนิมิต อ.เมือง จ.จันทบุรี',
  ARRAY['historic','architecture','photo','gems','heritage'], 4.8, true, true),

('blue-temple', 'วัดปากน้ำแขมหนู (โบสถ์สีน้ำเงิน)', 'Wat Pak Nam Khaem Nu (Blue Temple)', 'temple', 'ท่าใหม่',
  'โบสถ์วิจิตรตระการตาที่ใช้เซรามิกสีน้ำเงินขาวประดับตกแต่งเพื่อทนทานต่อไอเค็มของทะเล เป็นแลนด์มาร์กสำคัญในการมาไหว้พระขอพรและบันทึกภาพสถาปัตยกรรมที่สวยงามไม่เหมือนใคร',
  'A breathtaking temple decorated with blue-and-white ceramic to withstand sea salt corrosion. A major landmark for prayers and capturing one-of-a-kind architecture.',
  'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1200',
  12.5283, 101.9500, '06:00-18:00', 'ฟรี',
  'ต.ปากน้ำแขมหนู อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['architecture','photo','seaside','spiritual','hidden-gem'], 4.8, true, true),

('wat-khet', 'วัดเขตร์นาบุญญาราม', 'Wat Khet Na Bunyaram', 'temple', 'เมืองจันทบุรี',
  'วัดจีน-ญวนเก่าแก่ใจกลางชุมชนริมน้ำจันทบูรที่สร้างขึ้นตั้งแต่สมัยรัชกาลที่ 3 โดดเด่นด้วยสถาปัตยกรรมเอเชียตะวันออก เป็นศูนย์รวมความศรัทธาและการสืบทอดวัฒนธรรมของชาวจีน-ญวนในจันทบุรี',
  'An ancient Chinese-Vietnamese temple in the heart of Chanthaboon riverside community, built during King Rama III''s reign. Distinct East Asian architecture and a center of cultural heritage.',
  'https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=1200',
  12.6100, 102.1095, '06:00-18:00', 'ฟรี',
  'ชุมชนริมน้ำจันทบูร อ.เมือง จ.จันทบุรี',
  ARRAY['historic','architecture','heritage','riverside'], 4.5, true, false),

-- ============= HISTORY (8) =============
('chanthaboon-riverside', 'ชุมชนริมน้ำจันทบูร', 'Chanthaboon Riverside Community', 'history', 'เมืองจันทบุรี',
  'ย่านประวัติศาสตร์เก่าแก่กว่า 300 ปีที่ผสมผสานวัฒนธรรมไทย จีน และญวน เต็มไปด้วยอาคารไม้ทรงคลาสสิก คาเฟ่วินเทจ และงานสตรีทอาร์ตบนกำแพงที่สะท้อนวิถีชีวิตดั้งเดิมอันงดงาม',
  'A 300+ year-old historic community blending Thai, Chinese and Vietnamese cultures. Filled with classic wooden architecture, vintage cafes, and street art reflecting traditional lifeways.',
  'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1200',
  12.6075, 102.1083, '24 ชั่วโมง (ร้านส่วนใหญ่ 09:00-21:00)', 'ฟรี',
  'ถ.สุขาภิบาล อ.เมือง จ.จันทบุรี',
  ARRAY['heritage','architecture','riverside','cafe','street-art','photo','family'], 4.7, true, true),

('king-taksin-shrine', 'ศาลสมเด็จพระเจ้าตากสิน', 'King Taksin Shrine', 'history', 'เมืองจันทบุรี',
  'ศาลและค่ายตากสินที่พระเจ้าตากสินใช้เป็นฐานทัพรวบรวมไพร่พลกู้กรุงศรีอยุธยา มีพิพิธภัณฑ์ประวัติศาสตร์เล็กๆ บอกเล่าเรื่องราวการกอบกู้เอกราช',
  'Shrine and camp where King Taksin gathered forces to liberate Ayutthaya from Burmese rule. Small history museum recounts the independence struggle.',
  'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200',
  12.6133, 102.1108, '08:00-17:00', 'ฟรี',
  'ถ.ท่าหลวง อ.เมือง จ.จันทบุรี',
  ARRAY['historic','spiritual','museum','heritage'], 4.6, true, false),

('tuek-daeng', 'ตึกแดง', 'The Red Building', 'history', 'แหลมสิงห์',
  'อาคารอิฐแดงสมัยฝรั่งเศสยึดครองจันทบุรี (พ.ศ. 2436-2447) ปัจจุบันเป็นพิพิธภัณฑ์เล่าเรื่องประวัติศาสตร์ช่วงนั้น คู่กับคุกขี้ไก่ที่อยู่ใกล้กัน',
  'A red brick building from the French occupation of Chanthaburi (1893-1904). Now a museum recounting that era of history, alongside the nearby Kuk Khi Kai prison.',
  'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=1200',
  12.4708, 102.0617, '08:30-16:30 (ปิดวันจันทร์)', 'ฟรี',
  'อ.แหลมสิงห์ จ.จันทบุรี',
  ARRAY['historic','museum','colonial','seaside'], 4.4, true, false),

('house-69', 'ศูนย์การเรียนรู้ บ้านเลขที่ 69', 'House No. 69 Learning Center', 'history', 'เมืองจันทบุรี',
  'อาคารเก่าแก่อายุกว่าร้อยปีในชุมชนริมน้ำจันทบูรที่ถูกบูรณะและปรับปรุงให้เป็นศูนย์จัดแสดงเรื่องราว ประวัติศาสตร์ และวิถีชีวิตของการค้าขายในอดีตของเมืองจันท์',
  'A century-old building in Chanthaboon riverside community, restored as a learning center showcasing history and merchant life of old Chanthaburi.',
  'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?w=1200',
  12.6080, 102.1085, '09:00-17:00 (ปิดวันจันทร์)', 'ฟรี',
  'ชุมชนริมน้ำจันทบูร อ.เมือง จ.จันทบุรี',
  ARRAY['heritage','museum','riverside','education'], 4.5, true, false),

('gem-market', 'ตลาดพลอยจันทบุรี', 'Chanthaburi Gem Market', 'history', 'เมืองจันทบุรี',
  'ศูนย์ค้าพลอยที่ใหญ่ที่สุดในประเทศไทย เปิดเฉพาะวันศุกร์-อาทิตย์ มีพ่อค้าจากทั่วโลกมาซื้อขายทับทิม ไพลิน และพลอยอื่นๆ เป็นมรดกการค้าที่หล่อหลอมเอกลักษณ์ของเมืองจันท์',
  'Thailand''s largest gemstone trading hub, open Friday-Sunday only. International dealers trade rubies, sapphires, and other gems here. A trade legacy that shaped Chanthaburi''s identity.',
  'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=1200',
  12.6094, 102.1119, 'ศ.-อา. 10:00-15:00', 'ฟรีเข้าชม',
  'ถ.ศรีจันทร์ อ.เมือง จ.จันทบุรี',
  ARRAY['heritage','gems','shopping','culture'], 4.6, true, true),

('mee-jai-jewelry', 'เวิร์กชอปทำเครื่องประดับ มีใจ', 'Mee Jai Jewelry Workshop', 'history', 'เมืองจันทบุรี',
  'สถานที่เปิดประสบการณ์ตรงในการทำเครื่องประดับอัญมณีด้วยตนเอง เรียนรู้ศิลปะการออกแบบจากช่างฝีมือท้องถิ่น สัมผัสจิตวิญญาณของเมืองหลวงแห่งอัญมณีอย่างลึกซึ้ง',
  'Hands-on jewelry-making experience with local artisans. Learn design arts and feel the soul of the gem capital firsthand.',
  'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=1200',
  12.6090, 102.1100, '10:00-18:00 (ติดต่อล่วงหน้า)', '500-1500฿/คน',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['workshop','craft','gems','heritage','hands-on'], 4.7, false, false),

('nong-bua-community', 'ชุมชนขนมแปลก ริมคลองหนองบัว', 'Nong Bua Klong Strange Sweets Community', 'history', 'เมืองจันทบุรี',
  'ตลาดชุมชนริมน้ำที่รวบรวมขนมไทยพื้นบ้านที่หาทานยากและมีชื่อแปลกหู นักท่องเที่ยวจะได้สัมผัสวิถีชีวิตชาวบ้านริมคลองที่เรียบง่ายและสนับสนุนเศรษฐกิจท้องถิ่นโดยตรง',
  'A canalside community market featuring rare Thai sweets with curious names. Experience simple riverside life and directly support the local economy.',
  'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1200',
  12.5800, 102.0800, 'เสาร์-อาทิตย์ 09:00-15:00', 'ของกิน 20-80฿',
  'ริมคลองหนองบัว อ.เมือง จ.จันทบุรี',
  ARRAY['heritage','dessert','riverside','community','local-food'], 4.5, true, false),

('bang-sa-kao', 'ชุมชนทอเสื่อบ้านบางสระเก้า', 'Ban Bang Sa Kao Mat Weaving Community', 'history', 'แหลมสิงห์',
  'ชุมชนท่องเที่ยวที่ยังคงอนุรักษ์ภูมิปัญญาการทอเสื่อกก หรือ เสื่อจันทบูร อันเลื่องชื่อ นักท่องเที่ยวสามารถเรียนรู้กระบวนการจักสานและอุดหนุนผลิตภัณฑ์งานคราฟต์คุณภาพสูง',
  'A community preserving the famed Chanthabun reed mat weaving tradition. Visitors can learn weaving and support high-quality craft products.',
  'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200',
  12.5500, 102.0500, '08:00-17:00', 'ฟรีเข้าชม',
  'ต.บางสระเก้า อ.แหลมสิงห์ จ.จันทบุรี',
  ARRAY['heritage','workshop','craft','community'], 4.4, true, false),

-- ============= FOOD (5) =============
('krua-lung-choey', 'ครัวลุงเชย', 'Krua Lung Choey', 'food', 'เมืองจันทบุรี',
  'ร้านอาหารพื้นบ้านระดับตำนานคู่เมืองจันทบุรีที่เปิดมานานกว่า 15 ปี ขึ้นชื่อเรื่องเมนูท้องถิ่นรสชาติดั้งเดิม เช่น หมูชะมวง ผัดเผ็ดกระวาน และไก่ต้มกระวาน ในราคาย่อมเยาและคุ้มค่า',
  'A legendary local restaurant operating for 15+ years. Famous for authentic local dishes like mu chamuang (pork stewed in chamuang leaves), spicy stir-fried cardamom, and cardamom chicken — affordable and value-packed.',
  'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=1200',
  12.6100, 102.1100, '10:00-21:00', 'อาหาร 80-200฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['local-food','authentic','budget','family','spicy'], 4.7, false, true),

('poo-ja-tha-chalaeb', 'ปูจ๋า ท่าแฉลบ', 'Poo Ja Tha Chalaeb', 'food', 'แหลมสิงห์',
  'ร้านอาหารทะเลเก่าแก่ที่รับวัตถุดิบตรงจากท่าเรือ โดดเด่นด้วยเมนูซิกเนเจอร์อย่าง ปูจ๋า เนื้อแน่น หอมหวาน และอาหารทะเลพื้นบ้านที่ปรุงอย่างพิถีพิถันเพื่อรักษารสชาติของความสดใหม่',
  'A long-established seafood restaurant sourcing directly from the pier. Famous for signature poo-ja (stuffed crab shells) — dense, sweet, and aromatic — alongside meticulously prepared fresh seafood.',
  'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=1200',
  12.4700, 102.0500, '10:30-21:00', 'อาหาร 100-400฿',
  'ท่าแฉลบ อ.แหลมสิงห์ จ.จันทบุรี',
  ARRAY['local-food','seafood','authentic','signature','seaside'], 4.7, false, true),

('ruen-lumpoo', 'เรือนลำพูจันทบุรี', 'Ruen Lumpoo Chanthaburi', 'food', 'ท่าใหม่',
  'ร้านอาหารลับรสชาติเด็ดริมน้ำที่ใช้วัตถุดิบไซส์ใหญ่จากชาวประมงท้องถิ่น เสิร์ฟซีฟู้ดแบบจัดเต็มล้นจาน ปรุงรสจัดจ้านตามสไตล์คนจันท์แท้ๆ ไม่มีหวงเครื่อง',
  'A hidden riverside gem using huge ingredients straight from local fishermen. Generous seafood portions seasoned in true Chanthaburi style — bold and unsparing.',
  'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1200',
  12.5500, 101.9000, '11:00-21:00', 'อาหาร 150-500฿',
  'อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['local-food','seafood','riverside','hidden-gem','generous'], 4.6, false, false),

('krua-luk-khoey', 'ครัวลูกเขย', 'Krua Luk Khoey', 'food', 'ท่าใหม่',
  'ร้านอาหารลับสไตล์โมเดิร์นคูซีนอ่าวคุ้งกระเบนที่นำวัตถุดิบพื้นบ้านและอาหารทะเลสดใหม่มาประยุกต์เป็นเมนูฟิวชั่นสุดสร้างสรรค์ เช่น สปาเกตตีพริกแห้งไข่กุ้ง สร้างประสบการณ์การกินที่แปลกใหม่',
  'A hidden modern-cuisine spot near Kung Krabaen Bay, blending local ingredients and fresh seafood into creative fusion dishes like dried-chili shrimp-roe spaghetti — a fresh dining experience.',
  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1200',
  12.5500, 101.9100, '11:30-21:30', 'อาหาร 180-450฿',
  'อ่าวคุ้งกระเบน อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['local-food','seafood','fusion','hidden-gem','seaside','modern'], 4.6, false, false),

('chanthaburi-night-market', 'ตลาดโต้รุ่งจันทบุรี', 'Chanthaburi Night Market', 'food', 'เมืองจันทบุรี',
  'ตลาดกลางคืนที่มีอาหารท้องถิ่นจันทบุรีหลากหลาย ก๋วยเตี๋ยวเส้นจันท์ หมูชะมวง ผัดเส้นจันท์ทะเล ราคาย่อมเยา เหมาะสำหรับการเดินชิมลิ้มรสอาหารพื้นเมืองในบรรยากาศชาวบ้าน',
  'A vibrant night market with diverse local Chanthaburi cuisine — Chanthaburi noodles, mu chamuang, seafood pad sen-chan. Affordable and perfect for walking and sampling local flavors.',
  'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200',
  12.6097, 102.1100, '17:00-22:00', 'อาหาร 40-150฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['street-food','night-market','local-food','budget','family'], 4.5, true, false),

-- ============= CAFE (7) =============
('good-cafe', 'กู๊ด คาเฟ่ จันทบุรี', 'Good Cafe Chanthaburi', 'cafe', 'มะขาม',
  'คาเฟ่น่ารักที่ซ่อนตัวอยู่ในสวนผลไม้อันร่มรื่น นำเสนอเมนูเบเกอรี่โฮมเมดที่ทำจากผลไม้สดในพื้นที่ มีมุมถ่ายรูปที่สวยงามท่ามกลางธรรมชาติที่เงียบสงบ ตอบโจทย์การพักผ่อนแบบสโลว์ไลฟ์',
  'A charming cafe hidden in a lush fruit orchard. Homemade bakery using fresh local fruits, photogenic spots in serene nature — perfect for slow living.',
  'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200',
  12.7000, 102.2000, '09:00-18:00', 'เครื่องดื่ม 70-150฿',
  'อ.มะขาม จ.จันทบุรี',
  ARRAY['cafe','garden','slow-life','photo','fruit','homemade'], 4.7, false, true),

('mililin-cafe', 'มิลิลิน คาเฟ่', 'Mililin Cafe & Eatery', 'cafe', 'เมืองจันทบุรี',
  'คาเฟ่กึ่งร้านอาหารริมแม่น้ำในตัวเมือง ตกแต่งสไตล์โมเดิร์นมินิมอลโทนขาว-ดำ พร้อมโซนเอาท์ดอร์ที่ให้ความรู้สึกเหมือนกำลังแคมป์ปิ้ง ถ่ายรูปสวยทุกมุม และให้บรรยากาศร่มรื่น',
  'A cafe-cum-eatery on the riverbank in town. Modern minimal black-and-white decor with a camp-themed outdoor zone — photogenic from every angle.',
  'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=1200',
  12.6090, 102.1090, '08:00-20:00', 'เครื่องดื่ม 80-180฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['cafe','riverside','modern','minimal','photo','brunch'], 4.6, false, false),

('tree-house-cafe', 'ทรีเฮาส์ คาเฟ่', 'Tree House Cafe', 'cafe', 'ท่าใหม่',
  'คาเฟ่ในสวนสีเขียวที่พิถีพิถันเรื่องเมล็ดกาแฟ ไฮไลต์อยู่ที่เมนูเบเกอรี่และเครื่องดื่มที่รังสรรค์จากทุเรียนเมืองจันท์ เสิร์ฟในบรรยากาศที่โปร่งสบายทั้งโซนห้องแอร์และโซนสวนธรรมชาติ',
  'A green-garden cafe meticulous about coffee beans. Highlights: bakery and drinks crafted from Chanthaburi durian, served in airy indoor or outdoor garden zones.',
  'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=1200',
  12.5500, 102.0500, '08:30-19:00', 'เครื่องดื่ม 90-200฿',
  'อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['cafe','garden','durian','specialty-coffee','photo'], 4.5, false, false),

('asterisk-cafe', 'แอสเทอริสก์ คาเฟ่', 'ASTERISK CAFE', 'cafe', 'ท่าใหม่',
  'คาเฟ่ริมทะเลสไตล์อบอุ่นเป็นกันเองที่โดดเด่นด้วยเมนูกาแฟสเปเชียลตี้และเมล็ดกาแฟ Single Origin มีพื้นที่นั่งใต้ร่มไม้ใหญ่รับลมทะเลเย็นสบาย และสามารถเดินลงไปสัมผัสหาดทรายได้โดยตรง',
  'A warm, friendly beachside cafe specializing in single-origin specialty coffee. Seating under giant trees with cooling sea breeze, and direct beach access.',
  'https://images.unsplash.com/photo-1559496417-e7f25cb247f3?w=1200',
  12.4500, 101.8500, '08:00-19:00', 'เครื่องดื่ม 80-180฿',
  'หาดเจ้าหลาว อ.ท่าใหม่ จ.จันทบุรี',
  ARRAY['cafe','seaside','specialty-coffee','sunset','photo','romantic'], 4.7, false, true),

('mills-cafe', 'มิลส์ คาเฟ่', 'Mills Cafe', 'cafe', 'เมืองจันทบุรี',
  'ร้านกาแฟสไตล์ลอฟท์วินเทจดิบเท่ในตัวเมืองที่เน้นเสิร์ฟกาแฟคุณภาพสูงจากเมล็ดกาแฟไทย รสชาติเข้มข้นถูกใจคอกาแฟสายสโลว์บาร์ เหมาะสำหรับการแวะเติมพลังก่อนเดินทางต่อ',
  'A raw-loft vintage coffee shop in town serving high-quality Thai-origin coffee. Bold flavors loved by slow-bar enthusiasts — perfect for an energy refill before continuing the journey.',
  'https://images.unsplash.com/photo-1442975631115-c4f7b05b8a2c?w=1200',
  12.6100, 102.1095, '08:00-18:00', 'เครื่องดื่ม 70-150฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['cafe','specialty-coffee','vintage','loft','thai-coffee'], 4.5, false, false),

('tamajun-cafe', 'ตามาจัน คาเฟ่', 'Tamajun Cafe', 'cafe', 'เมืองจันทบุรี',
  'คาเฟ่ริมน้ำในชุมชนริมน้ำจันทบูร อาคารไม้เก่าตกแต่งวินเทจ บรรยากาศชิวมาก เหมาะถ่ายรูปและซึมซับวิถีชีวิตย้อนยุคของเมืองจันท์',
  'A riverside cafe in Chanthaboon riverside community. Vintage-decorated old wooden building — chill vibes, photogenic, and perfect for soaking up nostalgic Chanthaburi life.',
  'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1200',
  12.6080, 102.1085, '09:00-19:00', 'เครื่องดื่ม 60-150฿',
  'ชุมชนริมน้ำจันทบูร อ.เมือง จ.จันทบุรี',
  ARRAY['cafe','riverside','vintage','heritage','photo','slow-life'], 4.6, false, true),

('baan-luang-rajamaitri', 'บ้านหลวงราชไมตรี', 'Baan Luang Rajamaitri', 'cafe', 'เมืองจันทบุรี',
  'บ้านโบราณกว่า 150 ปีที่ปรับเป็นโรงแรมและคาเฟ่ ตกแต่งคลาสสิก กาแฟดี ขนมอร่อย เป็นมรดกของจันทบุรีที่ผสานความเป็นไทย-จีนได้อย่างลงตัว',
  'A 150+ year-old heritage house turned into a hotel and cafe. Classic decor, great coffee, delicious pastries — a cultural icon blending Thai-Chinese influences.',
  'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=1200',
  12.6087, 102.1085, '07:00-21:00', 'เครื่องดื่ม 80-130฿',
  'ชุมชนริมน้ำจันทบูร อ.เมือง จ.จันทบุรี',
  ARRAY['cafe','heritage','riverside','hotel','vintage','photo'], 4.7, false, false),

-- ============= NIGHTLIFE (5) =============
('krung-bar', 'กรุงบาร์', 'Krung Bar', 'nightlife', 'เมืองจันทบุรี',
  'บาร์ลับนั่งชิลที่เอาใจสายคราฟต์เบียร์ มีเบียร์นำเข้าชั้นนำและเบียร์สดให้เลือกหลากหลาย เสิร์ฟพร้อมเมนูกับแกล้มอร่อยๆ เคล้าเสียงดนตรีสดในบรรยากาศเป็นกันเอง ไม่วุ่นวาย',
  'A laid-back speakeasy for craft beer lovers. Wide selection of premium imported and draught beers, paired with tasty bites and live acoustic music in an unpretentious atmosphere.',
  'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1200',
  12.6100, 102.1100, '18:00-01:00 (ปิดวันจันทร์)', 'เครื่องดื่ม 120-280฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['craft-beer','live-music','speakeasy','chill','adult'], 4.6, false, true),

('bamboo-riverbar', 'แบมบู ริเวอร์บาร์', 'Bamboo Riverbar', 'nightlife', 'เมืองจันทบุรี',
  'ร้านแฮงเอาท์ริมแม่น้ำจันทบุรีที่บรรยากาศดีเยี่ยม เหมาะสำหรับการสังสรรค์ยามค่ำคืน มีโปรโมชันอาหารสุดคุ้ม พร้อมมุมถ่ายรูปแสงไฟนีออนสวยๆ ริมน้ำ',
  'A riverside hangout with great vibes for nighttime gatherings. Value-packed food promos and beautiful neon-lit photo spots by the water.',
  'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=1200',
  12.6080, 102.1085, '17:00-00:00', 'อาหาร+เครื่องดื่ม 200-500฿',
  'ริมแม่น้ำจันทบุรี อ.เมือง จ.จันทบุรี',
  ARRAY['riverside','hangout','photo','live-music','group'], 4.5, false, false),

('nova-rooftop', 'โนว่า จันทบุรี', 'NOVA Chanthaburi', 'nightlife', 'เมืองจันทบุรี',
  'บาร์สุดชิคบนดาดฟ้าที่ให้คุณชมวิวเมืองจันท์ยามค่ำคืนได้อย่างเต็มตา มีโซนห้องคาราโอเกะส่วนตัวที่ตกแต่งอย่างสวยงาม เหมาะสำหรับการจัดปาร์ตี้กับกลุ่มเพื่อนสนิท',
  'A chic rooftop bar with full panoramic views of Chanthaburi at night. Beautifully decorated private karaoke rooms — perfect for parties with close friends.',
  'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=1200',
  12.6105, 102.1095, '18:00-02:00', 'เครื่องดื่ม 150-350฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['rooftop','view','party','karaoke','group','adult'], 4.5, false, false),

('wonder-house', 'วันเดอร์ เฮาส์', 'Wonder House', 'nightlife', 'เมืองจันทบุรี',
  'ค็อกเทลบาร์ลับสุดพิเศษที่ตกแต่งอย่างมีเสน่ห์ด้วยแสงไฟสลัวและโคมไฟคริสตัล โดดเด่นด้วยเมนูเครื่องดื่มค็อกเทลซิกเนเจอร์ที่ชงอย่างพิถีพิถัน เหมาะสำหรับค่ำคืนสุดโรแมนติกหรือการออกเดท',
  'A special speakeasy cocktail bar charmingly decorated with dim lighting and crystal lamps. Signature meticulously crafted cocktails — perfect for romantic nights or dates.',
  'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200',
  12.6100, 102.1100, '19:00-01:00', 'ค็อกเทล 220-380฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['cocktail','speakeasy','romantic','date','adult','craft'], 4.6, false, false),

('martini-chanthaburi', 'มาร์ตินี่ จันทบุรี', 'Martini Chanthaburi', 'nightlife', 'เมืองจันทบุรี',
  'ร้านนั่งดื่มยอดฮิตใจกลางเมืองที่ผสมผสานความชิลหลังเลิกงานเข้ากับจังหวะดนตรีสดสนุกสนานในช่วงดึก มีเครื่องดื่มครบครันและอาหารทานเล่นที่เหมาะแก่การแชร์กับเพื่อนฝูง',
  'A popular city-center spot blending after-work chill with energetic late-night live music. Full drink menu and shareable bites — perfect with friends.',
  'https://images.unsplash.com/photo-1569924995012-c4c706bfcd51?w=1200',
  12.6100, 102.1098, '18:00-01:30', 'เครื่องดื่ม 130-280฿',
  'อ.เมือง จ.จันทบุรี',
  ARRAY['live-music','party','group','hangout','adult'], 4.4, false, false),

-- ============= FRUIT (6) =============
('kp-garden', 'สวนเคพี การ์เด้น', 'KP Garden Chanthaburi', 'fruit', 'มะขาม',
  'สวนผลไม้ที่ให้ประสบการณ์ท่องเที่ยวเชิงเกษตรอย่างสมบูรณ์แบบ มีกิจกรรมปั่นจักรยานชมสวน ให้อาหารสัตว์ และจุดเด่นคือบุฟเฟ่ต์ทุเรียนหมอนทองและผลไม้สดๆ ตามฤดูกาล',
  'A complete agrotourism experience: cycle through the orchard, feed animals, and enjoy the highlight — Monthong durian and seasonal fruit buffet.',
  'https://images.unsplash.com/photo-1574226516831-e1dff420e8f8?w=1200',
  12.7000, 102.2000, 'พ.ค.-ก.ค. 08:00-17:00', 'บุฟเฟ่ต์ 350-550฿',
  'อ.มะขาม จ.จันทบุรี',
  ARRAY['durian','buffet','family','cycling','agritourism','seasonal'], 4.7, false, true),

('suan-sao-sudjai', 'สวนสาวสุดใจ', 'Suan Sao Sudjai', 'fruit', 'แหลมสิงห์',
  'สวนผลไม้บรรยากาศอบอุ่นสไตล์ครอบครัวย่านแหลมสิงห์ เปิดให้นักท่องเที่ยวเดินชมสวนอย่างใกล้ชิดและชิมผลไม้สดๆ เด็ดจากต้น ทั้งทุเรียนเนื้อแน่น เงาะ และมังคุด',
  'A warm family-style orchard in Laem Sing. Walk through the garden up close and taste fresh-picked fruits — dense durian, rambutan, and mangosteen.',
  'https://images.unsplash.com/photo-1546548970-71785318a17b?w=1200',
  12.4700, 102.0700, 'พ.ค.-ก.ค. 08:00-17:00', '250-450฿',
  'อ.แหลมสิงห์ จ.จันทบุรี',
  ARRAY['durian','family','farm-tour','seasonal','seaside-area'], 4.6, false, true),

('suan-pa-eed', 'สวนทุเรียนป้าอิ๊ด วิถีธรรมชาติ', 'Pa Eed Natural Durian Orchard', 'fruit', 'มะขาม',
  'สวนทุเรียนที่ดูแลด้วยวิถีเกษตรอินทรีย์ ถือเป็นสวรรค์ของคนรักทุเรียนขนานแท้เพราะมีสายพันธุ์โบราณและหายากให้เลือกลิ้มลองมากกว่า 26 สายพันธุ์ สร้างประสบการณ์การกินที่เหนือระดับ',
  'An organic durian orchard — a heaven for true durian lovers with 26+ rare and ancient varieties to taste. A premium tasting experience.',
  'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=1200',
  12.6800, 102.2300, 'พ.ค.-ก.ค. 09:00-17:00', '500-1200฿',
  'อ.มะขาม จ.จันทบุรี',
  ARRAY['durian','organic','rare-variety','tasting','seasonal'], 4.8, false, false),

('baan-suan-chan-tungphel', 'บ้านสวนจันท์ ทุ่งเพล', 'Baan Suan Chan Tung Phel', 'fruit', 'เขาคิชฌกูฏ',
  'ลานกางเต็นท์ริมน้ำส่วนตัวหน้าบ้านพักสไตล์ลอฟท์ในย่านสวนผลไม้ทุ่งเพล ผู้เข้าพักสามารถลงเล่นน้ำ ล่องห่วงยาง หรือทำกิจกรรมปิ้งย่างได้อย่างสะดวกสบาย ถือเป็นสวรรค์ของการพักผ่อนแบบกลุ่มเพื่อนหรือครอบครัว',
  'Private streamside camping in front of a loft-style cabin in Tung Phel orchard area. Swim, tube, or BBQ — a paradise for groups and families.',
  'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=1200',
  12.7500, 102.2500, 'ตลอดปี (จองล่วงหน้า)', '800-2000฿/คืน',
  'ต.ทุ่งเพล อ.เขาคิชฌกูฏ จ.จันทบุรี',
  ARRAY['camping','homestay','riverside','fruit','group','family'], 4.6, false, false),

('baan-ing-than-tungphel', 'บ้านอิงธารโฮมสเตย์ ทุ่งเพล', 'Baan Ing Than Homestay Tung Phel', 'fruit', 'เขาคิชฌกูฏ',
  'ที่พักและลานกางเต็นท์บรรยากาศดีติดริมลำธารในย่านทุ่งเพล มีจุดกางเต็นท์บนดาดฟ้าเพื่อรับลมหนาว โอบล้อมด้วยธรรมชาติ สวนผลไม้ และเสียงน้ำตกที่สร้างความผ่อนคลายตลอดคืน',
  'Streamside homestay and camping with rooftop tent spots for cool breezes. Surrounded by nature, fruit orchards, and the sound of a waterfall — relaxing all night long.',
  'https://images.unsplash.com/photo-1487730116645-74489c95b41b?w=1200',
  12.7500, 102.2500, 'ตลอดปี (จองล่วงหน้า)', '700-1800฿/คืน',
  'ต.ทุ่งเพล อ.เขาคิชฌกูฏ จ.จันทบุรี',
  ARRAY['camping','homestay','riverside','fruit','quiet','nature'], 4.5, false, false),

('chanthaburi-fruit-festival', 'งานวันผลไม้และของดีจันทบุรี', 'Chanthaburi Fruit Festival', 'fruit', 'เมืองจันทบุรี',
  'งานประจำปีจัดในเดือน พ.ค.-มิ.ย. มีผลไม้สดจากสวนรอบจังหวัด ราคาถูก อาหารพื้นเมือง และการแสดงวัฒนธรรม เป็นโอกาสที่ดีในการลิ้มลองผลไม้คุณภาพสูงในราคาประหยัด',
  'Annual festival in May-June featuring fresh fruits from province-wide orchards at low prices, local food, and cultural performances — a great chance to taste premium fruits affordably.',
  'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=1200',
  12.6100, 102.1100, 'พ.ค.-มิ.ย. ตามประกาศ', 'ฟรีเข้างาน',
  'สนามกีฬาจังหวัดจันทบุรี',
  ARRAY['festival','seasonal','durian','culture','family','budget'], 4.7, true, false);
